In [31]:
def convert_units():
    """
    Convert between different units of measurement.
    Supports length, weight and volume conversions.
    """

    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = int(input("Enter choice: "))
        value = float(input("Enter value to convert: "))

        if choice == 1:
            print("1. meters to feet")
            print("2. feet to meters")
            sub = int(input("Select option: "))

            if sub == 1:
                result = value * 3.28084
                print("Feet:", result)
            elif sub == 2:
                result = value / 3.28084
                print("Meters:", result)

        elif choice == 2:
            print("1. kg to lbs")
            print("2. lbs to kg")
            sub = int(input("Select option: "))

            if sub == 1:
                print("Pounds:", value * 2.20462)
            elif sub == 2:
                print("Kilograms:", value / 2.20462)

        elif choice == 3:
            print("1. liters to gallons")
            print("2. gallons to liters")
            sub = int(input("Select option: "))

            if sub == 1:
                print("Gallons:", value * 0.264172)
            elif sub == 2:
                print("Liters:", value / 0.264172)

        else:
            print("Invalid choice")

    except ValueError:
        print("Invalid input. Please enter numeric values.")

convert_units()


Choose conversion type:
1. Length
2. Weight
3. Volume


Enter choice:  2
Enter value to convert:  60


1. kg to lbs
2. lbs to kg


Select option:  1


Pounds: 132.2772


In [3]:
def fsum(numbers):
    return sum(numbers)

def faverage(numbers):
    return sum(numbers) / len(numbers)

def fmax(numbers):
    return max(numbers)

def fmin(numbers):
    return min(numbers)

try:
    nums = list(map(float, input("Enter numbers separated by space: ").split()))

    print("Choose operation:")
    print("1 Sum")
    print("2 Average")
    print("3 Maximum")
    print("4 Minimum")

    choice = int(input("Choice: "))

    if choice == 1:
        print("Sum:", fsum(nums))
    elif choice == 2:
        print("Average:", faverage(nums))
    elif choice == 3:
        print("Max:", fmax(nums))
    elif choice == 4:
        print("Min:", fmin(nums))

except:
    print("Invalid input")


Enter numbers separated by space:  1 4 3 5 2 


Choose operation:
1 Sum
2 Average
3 Maximum
4 Minimum


Choice:  3


Max: 5.0


In [5]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))


[1, 3, 5]


In [7]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([10,20,30,40,50],1,3))


[20, 30, 40]


In [9]:
def sum_nested(lst):
    total = 0
    for i in lst:
        if isinstance(i, list):
            total += sum_nested(i)
        else:
            total += i
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))


21


In [11]:
def remove_element(lst, elem):
    result = []
    for i in lst:
        if isinstance(i, list):
            result.append(remove_element(i, elem))
        elif i != elem:
            result.append(i)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))


[[1], [3], [4, 5]]


In [13]:
def find_max(lst):
    maximum = float('-inf')

    for i in lst:
        if isinstance(i, list):
            maximum = max(maximum, find_max(i))
        else:
            maximum = max(maximum, i)

    return maximum

print(find_max([[1,2],[3,[4,5]],6]))


6


In [15]:
def count_occurrences(lst, elem):
    count = 0

    for i in lst:
        if isinstance(i, list):
            count += count_occurrences(i, elem)
        elif i == elem:
            count += 1

    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))


3


In [17]:
def deep_flatten(lst):
    result = []

    for i in lst:
        if isinstance(i, list):
            result.extend(deep_flatten(i))
        else:
            result.append(i)

    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))


[1, 2, 3, 4, 5, 6, 7, 8]


In [19]:
def average_nested(lst):

    flat = deep_flatten(lst)
    return sum(flat)/len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))


3.5


In [23]:
import numpy as np


In [35]:
a = np.empty((2,2))

b = np.ones((4,2))
c = np.full((3,3),7)

d = np.zeros_like(c)
e = np.ones_like(c)

new_list = [1,2,3,4]
f = np.array(new_list)

print(a)
print('\n')
print(b)
print('\n')
print(c)
print('\n')
print(d)
print('\n')
print(e)
print('\n')
print(f)


[[4.24399158e-314 1.06099790e-313]
 [1.27319747e-313 1.69759663e-313]]


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[7 7 7]
 [7 7 7]
 [7 7 7]]


[[0 0 0]
 [0 0 0]
 [0 0 0]]


[[1 1 1]
 [1 1 1]
 [1 1 1]]


[1 2 3 4]


In [37]:
a = np.arange(10,50)
print(a)
print('\n')

b = np.arange(9).reshape(3,3)
print(b)
print('\n')

c = np.eye(3)
print(c)
print('\n')

d = np.random.random(30)
print("Mean:", d.mean())
print('\n')

e = np.random.random((10,10))
print("Min:", e.min(), "Max:", e.max())
print('\n')

z = np.zeros(10)
z[4] = 1
print(z)
print('\n')

arr = np.array([1,2,0,0,4,0])
print(arr[::-1])
print(arr)
print('\n')

border = np.ones((5,5))
border[1:-1,1:-1] = 0
print(border)
print('\n')

checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Mean: 0.5223888937930226


Min: 0.0038575709521351254 Max: 0.9957234831670824


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


[0 4 0 0 2 1]
[1 2 0 0 4 0]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [39]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print('\n')
print(x-y)
print('\n')

print(x*3)
print('\n')

print(x**2)
print('\n')

print(np.dot(v,w))
print('\n')
print(np.dot(x,v))
print('\n')
print(np.dot(x,y))
print('\n')

print(np.vstack((x,y)))
print('\n')
print(np.column_stack((v,w)))
print('\n')

[[ 6  8]
 [10 13]]


[[-4 -4]
 [-4 -3]]


[[ 3  6]
 [ 9 15]]


[[ 1  4]
 [ 9 25]]


219


[29 77]


[[19 22]
 [50 58]]


[[1 2]
 [3 5]
 [5 6]
 [7 8]]


[[ 9 11]
 [10 12]]




In [43]:
#element wise add
import time
size = 1_000_000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [a + b for a, b in zip(list1, list2)]
end = time.time()

print("Python List Addition Time:", end - start)

Python List Addition Time: 0.07816410064697266


In [45]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result = arr1 + arr2
end = time.time()

print("NumPy Addition Time:", end - start)

NumPy Addition Time: 0.010099411010742188


In [47]:
#element wise multiplication
start = time.time()
result = [a * b for a, b in zip(list1, list2)]
end = time.time()

print("Python List Multiplication Time:", end - start)

Python List Multiplication Time: 0.07114410400390625


In [49]:
start = time.time()
result = arr1 * arr2
end = time.time()

print("NumPy Multiplication Time:", end - start)

NumPy Multiplication Time: 0.010180950164794922


In [53]:
#dot product
start = time.time()
dot = sum(a * b for a, b in zip(list1, list2))
end = time.time()

print("Python List Dot Product Time:", end - start)

Python List Dot Product Time: 0.12929177284240723


In [55]:
start = time.time()
dot = np.dot(arr1, arr2)
end = time.time()

print("NumPy Dot Product Time:", end - start)

NumPy Dot Product Time: 0.0010614395141601562


In [58]:
#matrix multiplication
size = 1000

A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()

result = [[sum(A[i][k] * B[k][j] for k in range(size)) 
           for j in range(size)] 
           for i in range(size)]

end = time.time()

print("Python List Matrix Multiplication Time:", end - start)

Python List Matrix Multiplication Time: 155.34398889541626


In [59]:
A = np.ones((1000,1000))
B = np.ones((1000,1000))

start = time.time()
result = np.dot(A, B)
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

NumPy Matrix Multiplication Time: 0.0449981689453125
